version: '3.9'
services:
  couchbase1:
    image: couchbase/server
    container_name: couchbase1
    volumes:
      - ./node1:/opt/couchbase/var
    ports:
      - 8101:8091
  couchbase2:
    image: couchbase/server
    container_name: couchbase2
    volumes:
      - ./node2:/opt/couchbase/var
    ports:
      - 8102:8091
  couchbase3:
    image: couchbase/server
    container_name: couchbase3
    volumes:
      - ./node3:/opt/couchbase/var
    ports:
      - 8103:8091
  couchbasemain:
    image: couchbase/server
    container_name: couchbasemain
    volumes:
      - ./nodeMain:/opt/couchbase/var
    ports:
      - 8201:8091
      - 8202:8092
      - 8203:8093
      - 8204:8094
      - 11210:11210
